version: "3.7"
services:
  influxdb:
    image: influxdb:2.1
    container_name: influxdb
    environment:
      - TZ=America/Jamaica
      - INFLUXD_REPORTING_DISABLED=true
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=admin
      - DOCKER_INFLUXDB_INIT_PASSWORD=${INFLUXDB_ADMIN_PASSWORD} # set in .env
      - DOCKER_INFLUXDB_INIT_ORG=ensom
      - DOCKER_INFLUXDB_INIT_BUCKET=solar

    ports:
      - 8086:8086
#    networks:
#      - fatheadl-net
    volumes:
      - /opt/influxdb2/data:/var/lib/influxdb2
      - /opt/influxdb2/config/influxdb.conf:/etc/influxdb/influxdb.conf:ro
    restart:
      unless-stopped
      
  grafana:
    image: grafana/grafana
    container_name: grafana
    environment:
      - TZ=${TIMEZONE}
      - GF_SERVER_DOMAIN=${PUBLIC_DOMAIN}
    user: "0"
    ports:
      - 3000:3000
    volumes:
      - /opt/grafana:/var/lib/grafana
      - /opt/grafana/provisioning/:/etc/grafana/provisioning/
      - /opt/grafana/grafana.ini:/etc/grafana/grafana.ini
      - /opt/grafana/dashboards:/etc/grafana/dashboards
    restart:
      unless-stopped
    networks:
#      - fatheadl-net      
#    labels:
      - traefik.enable=true
      - traefik.http.services.grafana.loadbalancer.server.port=3000
      - traefik.http.routers.grafana.rule=Host(`graf.${PUBLIC_DOMAIN}`)
      - traefik.http.routers.grafana.entrypoints=websecure
        #      - traefik.http.routers.homeassistant.tls=true
      - traefik.http.routers.grafana.tls.certresolver=le
#      - traefik.docker.network=fatheadl-net
      
  node-red:
 #   depends_on:
 #      - broker
    container_name: node-red
    image: nodered/node-red
    environment:
    #      - SET_CONTAINER_TIMEZONE=true
    #      - CONTAINER_TIMEZONE=${TIMEZONE}
      - TZ=${TIMEZONE}
    volumes:
      - "/opt/node-red:/data"
    user: "0"
    restart: unless-stopped
    network_mode: host
#    networks:
#      - localnet
#    ports:
#      - "1880:1880"

    labels:
      - traefik.enable=true
      - traefik.http.services.node-red.loadbalancer.server.port=1880
      - traefik.http.routers.node-red.rule=Host(`nr.${PUBLIC_DOMAIN}`)
      - traefik.http.routers.node-red.entrypoints=websecure
#      - traefik.http.routers.homeassistant.tls=true
      - traefik.http.routers.node-red.tls.certresolver=le
#      - traefik.docker.network=fatheadl-net     
      
      
      
networks:
  fatheadl-net:
    name: ubuntu_fatheadl-net
